version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:16.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local